---
driver:
  name: docker

provisioner:
  name: puppet_apply
  puppet_version: "latest"
  mainfests_path: manifests
  modules_path: modules

platforms:
  - name: centos-6.6

suites:
  - name: default
    manifest: site.pp
