---
driver:
  name: docker
  socket: tcp://192.168.59.103:2376

provisioner:
  name: puppet_apply
  mainfests_path: manifests
  modules_path: modules

platforms:
  - name: centos-6.6

suites:
  - name: default
    manifest: site.pp
